spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: admin
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8181

